"""
Gera as TABELAS e FIGURAS em ingles do manuscrito (latex/main.tex).

Por que um script separado, e nao uma flag nos geradores em portugues:

  1. os numeros ja estao todos em resultados/*.json, que sao versionados. Nada aqui
     retreina, reexecuta baseline nem precisa do venv com torch/transformers — roda
     com o Python global (numpy + matplotlib), como gerar_matriz_confusao.py;
  2. significancia_e_erros.py, que produz tres das sete tabelas, so roda no venv de
     3,5 GB e leva ~1h50 no caminho completo. Acrescentar saidas em ingles ali
     deixaria a versao em ingles refem de uma reexecucao cara;
  3. mexer nos geradores em portugues arrisca as saidas que sustentam o PDF ja
     compilado. Este script nao toca em nenhuma delas.

Como consequencia, o texto de rotulos e legendas esta duplicado entre os dois
caminhos, mas os NUMEROS nao: ambos leem os mesmos JSON, de modo que divergencia
numerica entre a versao em portugues e a em ingles e impossivel por construcao.
Se um resultado mudar, reexecute o gerador em portugues correspondente e depois
este script.

Entradas (todas em resultados/, versionadas):
  significancia.json           metricas do ensemble e dos tres baselines
  erros_taxonomia.json         matriz de confusao do conjunto de teste
  reranking_results.json       nDCG@k, P@k e MAP das quatro ordenacoes
  ablacao_score.json           as cinco funcoes de pontuacao
  estudo_caso_ordenacao.json   escores, separacao dos estratos e mudanca de ordem

Saidas (sem sufixo de idioma: nesta pasta so existe a versao em ingles --
a versao em portugues ficou na pasta do ESWA, de onde este artigo deriva):
  latex/tab-teste.tex, tab-baselines.tex, tab-significancia.tex,
        reranking_tabela.tex, tab-ablacao.tex, tab-estudo-caso.tex,
        tab-ordem.tex
  latex/figuras/en/fig02-confusion-matrix.png, fig05-reranking-evaluation.png,
        fig06-case-study-scores.png, fig07-case-study-order.png

As figuras em portugues, em latex/figuras/, nao sao tocadas: as duas versoes do
manuscrito compilam lado a lado.

CONVENCOES DA VERSAO EM INGLES
  - separador decimal e o PONTO, e milhar com virgula (o gerador em portugues faz o
    inverso);
  - ingles AMERICANO, como o manuscrito (a guideline do ESWA proibe misturar as duas
    variantes): behavior, favor, analyze;
  - nomes das classes traduzidos (Negativo -> Negative etc.), por serem categorias
    de anotacao e nao dado;
  - termos de consulta e titulos de video ficam no ORIGINAL em portugues, por serem
    entradas do sistema — a traducao vai na legenda, conforme a nota de idioma da
    Secao 1 do manuscrito.

Uso: python versao_en.py
"""

from __future__ import annotations

import json
import textwrap

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.transforms import blended_transform_factory

from caminhos import FIGURAS, LATEX, RESULTADOS, prepara_saidas

prepara_saidas()
FIGURAS_EN = FIGURAS / "en"
FIGURAS_EN.mkdir(parents=True, exist_ok=True)

AVISO = "% GENERATED BY src/experimentos/versao_en.py — do not edit by hand.\n"

# --- paleta e cromo ---------------------------------------------------------
# As classes de sentimento sao POLARES (Negativo <-> Positivo, com Neutro no
# meio), entao o esquema e DIVERGENTE: dois matizes opostos e um cinza neutro no
# centro. Azul<->vermelho, e nao verde<->vermelho: verde e vermelho sao o pior
# par possivel para deuteranopia e protanopia, justamente entre os dois polos.
COR_NEG = "#c1443c"
COR_NEU = "#898781"
COR_POS = "#2b7bba"
COR_CLASSE = {"Negativo": COR_NEG, "Neutro": COR_NEU, "Positivo": COR_POS}

# Re-ranking: as quatro ordenacoes NAO sao quatro categorias equivalentes. Duas
# sao LIMITES (o acaso, embaixo; o oraculo, em cima) e duas sao os metodos
# avaliados. Os limites vao em cinza tracejado, os metodos em cor cheia -- assim
# a figura diz "os metodos ficam entre o piso e o teto" sem precisar de legenda.
COR_SISTEMA = {"aleatorio": "#a8a7a1", "bloco": "#2a78d6",
               "sentenca": "#eb6834", "oraculo": "#52514e"}
ESTILO_SISTEMA = {"aleatorio": (1.4, "--"), "bloco": (2.0, "-"),
                  "sentenca": (2.0, "-"), "oraculo": (1.4, "--")}

# Estratos do estudo de caso: A (consulta de responsavel) contra B (animacao
# adulta com apelo infantil) -- de novo polaridade, mesmo par divergente.
COR_ESTRATO = {"A": COR_POS, "B": COR_NEG}

INK = "#0b0b0b"
INK_SUAVE = "#52514e"
GRADE = "#e1e0d9"
EIXO = "#c3c2b7"


def aplicar_estilo() -> None:
    """Estilo comum das figuras: o dado saturado, o cromo recuado."""
    plt.rcParams.update({
        "figure.dpi": 300,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.size": 9.5,
        "axes.titlesize": 10,
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 8.5,
        "axes.edgecolor": EIXO,
        "axes.linewidth": 0.8,
        "axes.labelcolor": INK_SUAVE,
        "axes.titlecolor": INK,
        "axes.grid": False,
        "grid.color": GRADE,
        "grid.linewidth": 0.6,
        "grid.linestyle": "-",
        "text.color": INK,
        "xtick.color": INK_SUAVE,
        "ytick.color": INK_SUAVE,
        "xtick.major.size": 0,
        "ytick.major.size": 0,
        "legend.frameon": False,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
    })


def _limpa(ax, eixo_grade="y"):
    """Tira as espinhas de cima e da direita e joga a grade para tras do dado."""
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color(EIXO)
    ax.set_axisbelow(True)
    if eixo_grade:
        ax.grid(axis=eixo_grade)

# Classes: sao categorias de anotacao, e por isso traduzidas. O que NAO se traduz e
# o dado (sentencas, consultas, titulos) — ver nota de idioma do manuscrito.
CLASSES = {"Negativo": "Negative", "Neutro": "Neutral", "Positivo": "Positive"}
LABELS = ["Negativo", "Neutro", "Positivo"]

# Rotulo dos baselines como aparecem em significancia.json
BASELINES = [
    ("SentiLex-PT", "SentiLex-PT"),
    ("TF-IDF + regressão logística", "TF-IDF + LR"),
    ("BERTimbau congelado + RL", "Frozen BERTimbau + LR"),
]
BASELINES_LONGO = {
    "SentiLex-PT": "SentiLex-PT",
    "TF-IDF + regressão logística": "TF-IDF + logistic regression",
    "BERTimbau congelado + RL": "Frozen BERTimbau + LR",
}


def le(nome: str) -> dict:
    caminho = RESULTADOS / nome
    if not caminho.exists():
        raise SystemExit(f"{nome} nao encontrado em {RESULTADOS}.")
    return json.loads(caminho.read_text(encoding="utf-8"))


def num(x, c=3):
    """Ponto decimal: a versao em ingles nao troca por virgula."""
    return f"{x:.{c}f}"


def escreve(nome: str, conteudo: str) -> None:
    (LATEX / nome).write_text(conteudo, encoding="utf-8")
    print(f"salvo: {nome}")


# --------------------------------------------------------------------- tabelas


def tab_teste(sig: dict) -> str:
    p = sig["proposto"]
    n = sig["n_teste"]
    linhas = [
        f"{CLASSES[c]} & {num(p['por_classe'][c]['precisao']*100,1)} & "
        f"{num(p['por_classe'][c]['recall']*100,1)} & "
        f"{num(p['por_classe'][c]['f1']*100,1)} \\\\"
        for c in LABELS
    ]
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Performance of the proposed ensemble on the held-out test set ({n} sentences). Values are percentages.}}\\label{{tab:teste}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LRRR@{{}}}}
\\toprule
Class / average & Precision & Recall & F1 \\\\
\\midrule
{chr(10).join(linhas)}
\\midrule
Macro & {num(p['precisao_macro']*100,2)} & {num(p['recall_macro']*100,2)} & {num(p['f1_macro']*100,2)} \\\\
Weighted & {num(p['precisao_ponderada']*100,2)} & {num(p['recall_ponderada']*100,2)} & {num(p['f1_ponderada']*100,2)} \\\\
\\midrule
\\multicolumn{{4}}{{@{{}}l}}{{Accuracy: {num(p['acuracia']*100,2)}}} \\\\
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


def tab_baselines(sig: dict) -> str:
    p = sig["proposto"]
    n = sig["n_teste"]
    linhas = []
    for chave, curto in BASELINES:
        c = sig["comparacoes"][chave]
        linhas.append(
            f"{curto} & {num(c['acuracia']*100,2)} & {num(c['f1_macro']*100,2)} & "
            + " & ".join(num(c["por_classe"][k]["f1"] * 100, 1) for k in LABELS)
            + " \\\\"
        )
    linhas.append(
        f"Fine-tuned BERTimbau (\\emph{{ensemble}}) & \\textbf{{{num(p['acuracia']*100,2)}}} & "
        f"\\textbf{{{num(p['f1_macro']*100,2)}}} & "
        + " & ".join(f"\\textbf{{{num(p['por_classe'][k]['f1']*100,1)}}}" for k in LABELS)
        + " \\\\"
    )
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Comparison against the baselines on the held-out test set ({n} sentences). Values are percentages.}}\\label{{tab:baselines}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LRRRRR@{{}}}}
\\toprule
Method & Accuracy & Macro F1 & F1 Neg. & F1 Neu. & F1 Pos. \\\\
\\midrule
{chr(10).join(linhas)}
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


def tab_significancia(sig: dict) -> str:
    n = sig["n_teste"]

    def pval(p):
        return "$< 10^{-4}$" if p < 1e-4 else f"${num(p, 4)}$"

    linhas = []
    for chave, _ in BASELINES:
        c = sig["comparacoes"][chave]
        bs = c["bootstrap_f1_macro"]
        linhas.append(
            f"{BASELINES_LONGO[chave]} & {num(c['f1_macro']*100,2)} & "
            f"{num(bs['diferenca']*100,2)} & "
            # virgula, e nao o ponto-e-virgula do gerador em portugues: o texto corrido
            # do manuscrito em ingles escreve os intervalos como [1.81, 9.02].
            f"[{num(bs['ic95'][0]*100,2)}, {num(bs['ic95'][1]*100,2)}] & "
            f"{pval(bs['p'])} & {pval(c['mcnemar']['p'])} \\\\"
        )
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Significance of the differences between the proposed \\emph{{ensemble}} and each baseline, on the same test partition ({n} sentences). $\\Delta$F1 is the macro-F1 difference in percentage points, in favor of the proposed model; the interval and the $p$-value come from a paired bootstrap with 10,000 resamples. The last column reports the $p$-value of McNemar's test on accuracy.}}\\label{{tab:significancia}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LRRRRR@{{}}}}
\\toprule
Baseline & Macro F1 & $\\Delta$F1 & 95\\% CI & $p$ (bootstrap) & $p$ (McNemar) \\\\
\\midrule
{chr(10).join(linhas)}
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


RERANK_ROTULOS = {
    "aleatorio": "Random ordering",
    "bloco": "Score, single block (Eq. 1)",
    "sentenca": "Score, sentence average",
    "oraculo": "Oracle (human labels)",
}
RERANK_ORDEM = ["aleatorio", "bloco", "sentenca", "oraculo"]


def tab_reranking(rr: dict) -> str:
    prot, res = rr["protocolo"], rr["resultados"]
    ks = prot["ks"]
    linhas = []
    for sis in RERANK_ORDEM:
        r = res[sis]
        vals = [num(r[f"ndcg@{k}"]) for k in ks] + [num(r[f"p@{k}"]) for k in ks] + [num(r["map"])]
        linhas.append(f"{RERANK_ROTULOS[sis]} & " + " & ".join(vals) + " \\\\")
    cab = " & ".join([f"nDCG@{k}" for k in ks] + [f"P@{k}" for k in ks] + ["MAP"])
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Re-ranking evaluation over {prot['n_consultas']} queries derived from the corpus titles ({prot['n_videos']} videos, out-of-fold prediction). The baseline is a random ordering, averaged over {prot['n_permutacoes_aleatorio']} permutations; the oracle ranks by the Score computed on the human labels.}}\\label{{tab:reranking}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LRRRRRRR@{{}}}}
\\toprule
Ordering & {cab} \\\\
\\midrule
{chr(10).join(linhas)}
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


ABLACAO_ROTULOS = {
    "proposta": "Equation~\\ref{eq:score}, as proposed",
    "plato_constante": "Safe band without tone gradation",
    "sem_confianca": "Negative band without the confidence term",
    "neutro_intermediario": "Neutral as intermediate risk",
    "esperanca": "Expectation alone, without the bands",
}

ABLACAO_METRICAS = ("ndcg@3", "ndcg@10", "p@3", "map")


def tab_ablacao(payload: dict) -> str:
    n_desempates = payload["n_desempates"]
    ab = payload["variantes"]
    linhas = []
    for chave, d in ab.items():
        m, s = d["metricas"], d["desvio_desempate"]
        nome = ABLACAO_ROTULOS[chave]
        if chave == "proposta":
            nome = f"\\textbf{{{nome}}}"
        cels = " & ".join(
            num(m[k]) if s[k] < 5e-4 else f"{num(m[k])}\\,$\\pm$\\,{num(s[k])}"
            for k in ABLACAO_METRICAS
        )
        linhas.append(f"{nome} & {cels} & {d['n_valores_distintos']}/{d['n_videos']} \\\\")
    n_videos = next(iter(ab.values()))["n_videos"]
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Ablation of the scoring function over the same \\emph{{out-of-fold}} predictions and the same queries of Section~\\ref{{sec:reranking}}. Each value is the mean over {n_desempates} draws of the input order, with the standard deviation shown whenever the variant ties videos; without the draw, variants that tie would be credited with the arbitrary video-ID order. The last column gives how many distinct score values the variant produces over the {n_videos} videos.}}\\label{{tab:ablacao}}
\\begin{{tabularx}}{{\\tblwidth}}{{@{{}}>{{\\raggedright\\arraybackslash}}Xrrrrr@{{}}}}
\\toprule
Scoring function & nDCG@3 & nDCG@10 & P@3 & MAP & Values \\\\
\\midrule
{chr(10).join(linhas)}
\\bottomrule
\\end{{tabularx}}
\\end{{table}}
"""


def tab_estudo_caso(ec: dict) -> str:
    por_termo = ec["por_termo"]
    e = ec["separacao_estratos"]["score_bloco"]
    linhas = []
    for termo, v in sorted(por_termo.items(), key=lambda kv: (kv[1]["estrato"], -kv[1]["media"])):
        est = "A" if v["estrato"].startswith("A") else "B"
        linhas.append(
            f"{est} & \\emph{{{termo}}} & {v['n']} & {num(v['media'])} & "
            f"{num(v['min'])} & {num(v['max'])} & {num(v['amplitude'])} \\\\"
        )
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Distribution of the \\emph{{Safety Score}} across the four case-study queries, ten videos each. In stratum~A the desirable behavior is that scores be high and close to one another, since there is no risk to correct; in stratum~B, that they be low. Queries are reproduced verbatim in Portuguese because they are inputs to the system: \\emph{{vídeo educativo para crianças}} `educational video for children'; \\emph{{desenho animado infantil}} `cartoon for children'; \\emph{{south park português dublado}} `south park portuguese dubbed'; \\emph{{rick and morty engraçado}} `rick and morty funny'.}}\\label{{tab:estudo-caso}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LLRRRRR@{{}}}}
\\toprule
Stratum & Query & $n$ & Mean & Min. & Max. & Range \\\\
\\midrule
{chr(10).join(linhas)}
\\midrule
\\textbf{{A}} & \\emph{{pooled}} & 20 & \\textbf{{{num(e['media_A'])}}} & {num(e['min_A'])} & {num(e['max_A'])} & {num(e['max_A'] - e['min_A'])} \\\\
\\textbf{{B}} & \\emph{{pooled}} & 20 & \\textbf{{{num(e['media_B'])}}} & {num(e['min_B'])} & {num(e['max_B'])} & {num(e['max_B'] - e['min_B'])} \\\\
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


def tab_ordem(ec: dict) -> str:
    linhas = []
    for termo, v in sorted(ec["mudanca_de_ordem"].items(), key=lambda kv: kv[1]["estrato"]):
        est = "A" if v["estrato"].startswith("A") else "B"
        linhas.append(
            f"{est} & \\emph{{{termo}}} & {num(v['kendall_tau'])} & "
            f"{num(v['top3_sobreposicao'], 2)} & {num(v['deslocamento_medio'], 1)} & "
            f"{v['primeiro_do_youtube']['para']}\\textsuperscript{{th}} & "
            f"{num(v['amplitude_score'])} \\\\"
        )
    corpo = "\n".join(linhas)
    # 1st/5th/7th: o gerador em portugues escreve sempre "o"; em ingles o sufixo
    # depende do numero, e so quatro valores ocorrem.
    for de, para in (("1\\textsuperscript{th}", "1\\textsuperscript{st}"),):
        corpo = corpo.replace(de, para)
    return f"""{AVISO}\\begin{{table}}[!t]
\\caption{{Effect of re-ranking on the ordering returned by the platform. $\\tau$ is Kendall's coefficient between the two orderings: $1$ means an ordering identical to YouTube's, and values near zero, an ordering unrelated to it. ``Top-3'' is the fraction of the platform's first three results that remain in the first three; ``Displacement'' is the mean absolute change in position; ``YouTube's 1\\textsuperscript{{st}}'' is the position to which the platform's top-ranked video was moved. The last column gives the range of scores within the query, which is what makes re-ranking meaningful or vacuous. Query glosses are given in Table~\\ref{{tab:estudo-caso}}.}}\\label{{tab:ordem}}
\\begin{{tabular*}}{{\\tblwidth}}{{@{{}}LLRRRRR@{{}}}}
\\toprule
Stratum & Query & $\\tau$ & Top-3 & Displacement & YouTube's 1\\textsuperscript{{st}} & Range \\\\
\\midrule
{corpo}
\\bottomrule
\\end{{tabular*}}
\\end{{table}}
"""


# --------------------------------------------------------------------- figuras


def fig_matriz_confusao(tax: dict) -> None:
    cm = np.array(tax["matriz_confusao"])
    labels = [CLASSES[c] for c in tax["labels"]]

    fig, ax = plt.subplots(figsize=(4.4, 3.8))
    vmax = cm.max()
    # Sequencial de matiz unico: a magnitude e a luminosidade.
    im = ax.imshow(cm, cmap="Blues", vmin=0, vmax=vmax)
    for i in range(3):
        for j in range(3):
            val = int(cm[i, j])
            pct = val / cm[i].sum() * 100 if cm[i].sum() else 0
            ax.text(j, i, f"{val}\n{pct:.1f}%", ha="center", va="center",
                    fontsize=9.5, color="white" if val > vmax * 0.55 else INK)
    ax.set_xticks([0, 1, 2])
    ax.set_yticks([0, 1, 2])
    ax.set_xticklabels(labels)
    ax.set_yticklabels(labels)
    ax.set_xlabel("Predicted class", labelpad=8)
    ax.set_ylabel("True class", labelpad=8)
    # Sem moldura e sem barra de cor: a celula ja traz numero e percentual, e a
    # escala continua seria decoracao redundante.
    ax.spines[["top", "right", "left", "bottom"]].set_visible(False)
    ax.tick_params(length=0)
    plt.tight_layout()
    plt.savefig(FIGURAS_EN / "fig02-confusion-matrix.png", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print("salvo: figuras/en/fig02-confusion-matrix.png")


def fig_reranking(rr: dict) -> None:
    res, ks = rr["resultados"], rr["protocolo"]["ks"]

    fig, eixos = plt.subplots(1, 2, figsize=(9.0, 3.2))
    for sis in RERANK_ORDEM:
        larg_linha, traco = ESTILO_SISTEMA[sis]
        eixos[0].plot(ks, [res[sis][f"ndcg@{k}"] for k in ks], marker="o",
                      markersize=4, label=RERANK_ROTULOS[sis],
                      color=COR_SISTEMA[sis], linewidth=larg_linha, linestyle=traco)
    eixos[0].set_xlabel("k")
    eixos[0].set_ylabel("nDCG@k")
    eixos[0].set_title("Ranking quality (nDCG@k)")
    eixos[0].set_xticks(ks)
    eixos[0].set_ylim(0, 1.05)
    _limpa(eixos[0], "y")
    eixos[0].legend(loc="lower right")

    grupos = [f"P@{k}" for k in ks] + ["MAP"]
    chaves = [f"p@{k}" for k in ks] + ["map"]
    x = np.arange(len(grupos))
    larg = 0.2
    for i, sis in enumerate(RERANK_ORDEM):
        # Piso e teto ficam esmaecidos tambem nas barras, para que a comparacao
        # que importa -- entre os dois metodos -- salte primeiro.
        limite = sis in ("aleatorio", "oraculo")
        eixos[1].bar(x + (i - 1.5) * larg, [res[sis][c] for c in chaves],
                     larg * 0.88, label=RERANK_ROTULOS[sis],
                     color=COR_SISTEMA[sis], alpha=0.55 if limite else 1.0)
    eixos[1].set_xticks(x)
    eixos[1].set_xticklabels(grupos)
    eixos[1].set_ylabel("value")
    eixos[1].set_title("Precision at the top and MAP")
    eixos[1].set_ylim(0, 1.05)
    _limpa(eixos[1], "y")

    fig.tight_layout()
    fig.savefig(FIGURAS_EN / "fig05-reranking-evaluation.png", dpi=300)
    plt.close(fig)
    print("salvo: figuras/en/fig05-reranking-evaluation.png")


def figs_estudo_caso(ec: dict) -> None:
    """Duas figuras separadas, pelo mesmo motivo de gerar_tabelas_estudo_caso.py.

    Os rotulos do eixo x sao os TERMOS DE CONSULTA, mantidos em portugues por serem
    entradas do sistema; a traducao vai na legenda da figura no manuscrito.
    """
    videos = ec["videos"]
    termos = list(dict.fromkeys(v["termo"] for v in videos))
    cores = COR_ESTRATO

    fig1, ax1 = plt.subplots(figsize=(7.2, 3.6))

    # As duas faixas da Eq. (2) sombreadas ao fundo: a distancia entre elas e tres
    # vezes a variacao interna, que e o argumento da formulacao em forma visual.
    ax1.axhspan(0.70, 0.85, color=cores["A"], alpha=0.09, zorder=0)
    ax1.axhspan(0.10, 0.2333, color=cores["B"], alpha=0.09, zorder=0)
    ax1.text(len(termos) - 0.42, 0.775, "no-risk band", fontsize=6.5,
             color=cores["A"], ha="right", va="center", zorder=1)
    ax1.text(len(termos) - 0.42, 0.167, "risk band", fontsize=6.5,
             color=cores["B"], ha="right", va="center", zorder=1)

    for i, termo in enumerate(termos):
        vs = [v for v in videos if v["termo"] == termo]
        est = "A" if vs[0]["estrato"].startswith("A") else "B"
        y = [v["score_bloco"] for v in vs]
        x = np.random.default_rng(7 + i).normal(i, 0.07, len(y))
        # Anel de superficie de 2px nas marcas sobrepostas: separa pontos
        # empilhados sem desenhar contorno decorativo em cada um.
        ax1.scatter(x, y, s=34, alpha=0.85, color=cores[est], edgecolor="white",
                    linewidth=0.8, zorder=3)
        ax1.plot([i - 0.28, i + 0.28], [np.mean(y)] * 2, color=INK, lw=1.6, zorder=4)

    ax1.set_xticks(range(len(termos)))
    ax1.set_xticklabels([textwrap.fill(t, 15) for t in termos], fontsize=7.5)
    ax1.set_ylabel("Safety Score")
    ax1.set_ylim(0, 1.05)
    ax1.axhline(0.5, color=EIXO, ls="--", lw=0.9, zorder=1)
    _limpa(ax1, "y")
    ax1.set_title("Score by query")
    for est, rot in (("A", "Stratum A (caregiver query)"), ("B", "Stratum B (child appeal)")):
        ax1.scatter([], [], color=cores[est], label=rot, s=42)
    ax1.legend(loc="lower left")
    fig1.tight_layout()
    fig1.savefig(FIGURAS_EN / "fig06-case-study-scores.png", dpi=300)
    plt.close(fig1)
    print("salvo: figuras/en/fig06-case-study-scores.png")

    fig2, ax2 = plt.subplots(figsize=(7.2, 4.0))
    cor_classe = COR_CLASSE
    largura, folga = 0.72, 1.55
    for i, termo in enumerate(termos):
        x0 = i * folga
        x1 = x0 + largura
        do_termo = [v for v in videos if v["termo"] == termo]
        for v in do_termo:
            d_ = next(x for x in ec["deslocamentos"]
                      if x["titulo"] == v["titulo"] and x["termo"] == v["termo"])
            ax2.plot([x0, x1], [d_["de"], d_["para"]], color=cor_classe[v["classe"]],
                     alpha=0.8, lw=1.2, marker="o", ms=3.0, zorder=3)
        # Rotulo do estrato acima da moldura, nao dentro dela — ver a nota equivalente
        # em gerar_tabelas_estudo_caso.py. As duas figuras tem de sair iguais.
        est = "A" if do_termo[0]["estrato"].startswith("A") else "B"
        ax2.text(x0 + largura / 2, 1.02, est,
                 transform=blended_transform_factory(ax2.transData, ax2.transAxes),
                 ha="center", va="bottom", fontsize=9,
                 fontweight="bold", color=cores[est])

    ax2.set_xlim(-0.35, (len(termos) - 1) * folga + largura + 0.35)
    ax2.set_xticks([i * folga + largura / 2 for i in range(len(termos))])
    ax2.set_xticklabels([textwrap.fill(t, 15) for t in termos], fontsize=7.5)
    ax2.set_ylabel("Position")
    ax2.invert_yaxis()
    ax2.set_yticks(range(1, 11))
    ax2.set_ylim(10.6, -0.6)
    _limpa(ax2, "y")
    ax2.set_title("YouTube ordering (left) $\\rightarrow$ Score ordering (right)",
                  fontsize=10, pad=18)
    manipuladores = [plt.Line2D([], [], color=cor, lw=2, label=CLASSES[cl])
                     for cl, cor in cor_classe.items()]
    fig2.legend(handles=manipuladores, loc="lower center", ncol=3, fontsize=8,
                frameon=False, title="Class predicted for the video", title_fontsize=8)
    fig2.tight_layout(rect=(0, 0.10, 1, 1))
    fig2.savefig(FIGURAS_EN / "fig07-case-study-order.png", dpi=300)
    plt.close(fig2)
    print("salvo: figuras/en/fig07-case-study-order.png")


def main():
    aplicar_estilo()

    sig = le("significancia.json")
    tax = le("erros_taxonomia.json")
    rr = le("reranking_results.json")
    ab = le("ablacao_score.json")
    ec = le("estudo_caso_ordenacao.json")

    escreve("tab-teste.tex", tab_teste(sig))
    escreve("tab-baselines.tex", tab_baselines(sig))
    escreve("tab-significancia.tex", tab_significancia(sig))
    escreve("reranking_tabela.tex", tab_reranking(rr))
    escreve("tab-ablacao.tex", tab_ablacao(ab))
    escreve("tab-estudo-caso.tex", tab_estudo_caso(ec))
    escreve("tab-ordem.tex", tab_ordem(ec))

    fig_matriz_confusao(tax)
    fig_reranking(rr)
    figs_estudo_caso(ec)

    print(f"\ntabelas em {LATEX}, figuras em {FIGURAS_EN}")


if __name__ == "__main__":
    main()
